sudo: required
dist: trusty
addons:
  apt:
    packages:
      gcc-multilib
      qemu
      gperf
      libtool
      texinfo
      help2man
language: c
cache:
  directories:
   - $HOME/.cache
env:
 - ARCH=i386
 - ARCH=powerpc
install: ./build.sh
script: ./test.sh
