sudo: required
dist: trusty
addons:
  apt:
    packages:
      gcc-multilib
      qemu
language: c
install: make -C i386
script:  timeout 60 qemu-system-i386 -no-reboot -kernel i386/os.elf -m 128 -display none -serial stdio
